name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - knoake
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: Posting a statement fails with a 400 error
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior

        A unit test or example would be very helpful.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The statement is successfully posted with a 201 response status code
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens.
      placeholder: The statement is not posted and a 400 response status code is returned
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      description: Any additional information that might be useful
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.x
        - 2.x
        - 3.x
        - 4.x
        - 5.x
    validations:
      required: true
