name: Enhancement request
description: Suggest an enhancement for this project
title: "[Enhancement]: "
labels: ["enhancement", "triage"]
assignees:
  - knoake
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!
  - type: textarea
    id: what
    attributes:
      label: What
      description: What does the enhancement do?
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why is the enhancement useful?
      placeholder: So that I can...
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any other information or screenshots about the enhancement.
      placeholder: Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
